services:
  # ====== H2 (tu setup actual) ======
  expense-tracker:
    build: .
    image: expense-tracker:latest
    container_name: expense-tracker
    profiles: ["h2"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./data:/app/data

  # ====== Postgres ======
  db:
    image: postgres:16-alpine
    container_name: expense-db
    profiles: ["pg"]
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  expense-tracker-pg:
    build: .
    image: expense-tracker:latest
    container_name: expense-tracker-pg
    profiles: ["pg"]
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-pg

volumes:
  pgdata:
